name: Build APK

on:
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: CI

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Decode Keystore and Setup for Release Build
        env:
          KEYSTORE_BASE64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD_SECRET: ${{ secrets.KEYSTORE_PASSWORD }} 
          KEY_ALIAS_SECRET: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD_SECRET: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_FILE_PATH: app/release.jks
          GRADLE_KEYSTORE_FILE_PATH: release.jks
        run: |
          echo "Decoding Keystore..."
          echo $KEYSTORE_BASE64 | base64 --decode > $KEYSTORE_FILE_PATH
          echo "Keystore decoded to $KEYSTORE_FILE_PATH"
          echo "KEYSTORE_FILE=$GRADLE_KEYSTORE_FILE_PATH" >> $GITHUB_ENV
          echo "KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD_SECRET" >> $GITHUB_ENV
          echo "KEY_ALIAS=$KEY_ALIAS_SECRET" >> $GITHUB_ENV
          echo "KEY_PASSWORD=$KEY_PASSWORD_SECRET" >> $GITHUB_ENV
          echo "Release signing environment variables set."

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/app-arm64-v8a-release.apk
